//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdixPay.Notifications.Contracts.Resources.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OdixPay.Notifications.Contracts.Resources.LocalizationResources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}.
        /// </summary>
        public static string AnUnexpectedErrorOccurredWithDetails {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNotificationRequest cannot be null..
        /// </summary>
        public static string CreateNotificationRequestCannotBeNull {
            get {
                return ResourceManager.GetString("CreateNotificationRequestCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send notification..
        /// </summary>
        public static string FailedToSendNotification {
            get {
                return ResourceManager.GetString("FailedToSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required..
        /// </summary>
        public static string IdIsRequired {
            get {
                return ResourceManager.GetString("IdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email recipient provided..
        /// </summary>
        public static string InvalidEmailRecipientProvided {
            get {
                return ResourceManager.GetString("InvalidEmailRecipientProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPushRecipientProvided.
        /// </summary>
        public static string InvalidPushRecipientProvided {
            get {
                return ResourceManager.GetString("InvalidPushRecipientProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SMS recipient provided..
        /// </summary>
        public static string InvalidSMSRecipientProvided {
            get {
                return ResourceManager.GetString("InvalidSMSRecipientProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template variables provided..
        /// </summary>
        public static string InvalidTemplateVariablesProvided {
            get {
                return ResourceManager.GetString("InvalidTemplateVariablesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value For The Given Type.
        /// </summary>
        public static string InvalidValueForTheGivenType {
            get {
                return ResourceManager.GetString("InvalidValueForTheGivenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification ID cannot be empty..
        /// </summary>
        public static string NotificationIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("NotificationIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification recipient not found..
        /// </summary>
        public static string NotificationRecipientNotFound {
            get {
                return ResourceManager.GetString("NotificationRecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification template not found..
        /// </summary>
        public static string NotificationTemplateNotFound {
            get {
                return ResourceManager.GetString("NotificationTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission must be specified in AuthorizeRole filter.
        /// </summary>
        public static string PermissionMustBeSpecifiedInAuthorizeRoleFilter {
            get {
                return ResourceManager.GetString("PermissionMustBeSpecifiedInAuthorizeRoleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource created successfully..
        /// </summary>
        public static string ResourceCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ResourceCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with ID &apos;{0}&apos; is currently in use and cannot be deleted..
        /// </summary>
        public static string TemplateInUseCannotBeDeleted {
            get {
                return ResourceManager.GetString("TemplateInUseCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template variables do not match..
        /// </summary>
        public static string TemplateVariablesDoNotMatch {
            get {
                return ResourceManager.GetString("TemplateVariablesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with ID &apos;{0}&apos; not found..
        /// </summary>
        public static string TemplateWithIdNotFound {
            get {
                return ResourceManager.GetString("TemplateWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with name &apos;{0}&apos; already exists..
        /// </summary>
        public static string TemplateWithNameAlreadyExisit {
            get {
                return ResourceManager.GetString("TemplateWithNameAlreadyExisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with name &apos;{0}&apos; already exists..
        /// </summary>
        public static string TemplateWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("TemplateWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        public static string TheRequestedResourceWasNotFound {
            get {
                return ResourceManager.GetString("TheRequestedResourceWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred..
        /// </summary>
        public static string UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a token set for this type.
        /// </summary>
        public static string UserAlreadyHasATokenSetForThisType {
            get {
                return ResourceManager.GetString("UserAlreadyHasATokenSetForThisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID cannot be null or empty..
        /// </summary>
        public static string UserIdCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("UserIdCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID claim is missing or empty.
        /// </summary>
        public static string UserIDClaimIsMissingOrEmpty {
            get {
                return ResourceManager.GetString("UserIDClaimIsMissingOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is required..
        /// </summary>
        public static string UserIdIsRequired {
            get {
                return ResourceManager.GetString("UserIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID not found in claims..
        /// </summary>
        public static string UserIDNotFoundInClaims {
            get {
                return ResourceManager.GetString("UserIDNotFoundInClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized for the requested action.
        /// </summary>
        public static string UserIsNotAuthorizedForTheRequestedAction {
            get {
                return ResourceManager.GetString("UserIsNotAuthorizedForTheRequestedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authenticated.
        /// </summary>
        public static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User request cannot be null or empty..
        /// </summary>
        public static string UserRequestCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("UserRequestCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role claim is missing or empty.
        /// </summary>
        public static string UserRoleClaimIsMissingOrEmpty {
            get {
                return ResourceManager.GetString("UserRoleClaimIsMissingOrEmpty", resourceCulture);
            }
        }
    }
}
